### ISSUE TITLE
furl().url setter throws AttributeError

### ISSUE THREAD

**Issue by ypomortsev** [gruns/furl#98]
With furl-1.0.1:

```>>> from furl import furl
>>> f = furl()
>>> f.url = 'http://example.com'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/ypomortsev/foo/lib/python3.5/site-packages/furl/furl.py", line 1665, in __setattr__
    object.__setattr__(self, attr, value)
  File "/usr/local/google/home/ypomortsev/foo/lib/python3.5/site-packages/furl/furl.py", line 1368, in url
    return self._parse(url)
AttributeError: 'furl' object has no attribute '_parse'
```

**Comment by gruns** [comment]
Wonderful catch!

Fixed in https://github.com/gruns/furl/commit/0548358e53bf23b7bf377424fb754bf653b7645a. This fix will ship in the next version of furl, v1.0.2.

Thank you for bringing this issue to my attention, Yegor. Don't hesitate to let
me know if there's anything else I can do for you.
